# Generated by Django 4.0.5 on 2022-07-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact',
            new_name='content',
        ),
        migrations.AddField(
            model_name='contact',
            name='participants',
            field=models.ManyToManyField(to='contact.participant'),
        ),
    ]
